name: AnimationCore
version: '${version}'
main: com.spectrasonic.animationsCore.Main
description: 'Advanced animation system for Minecraft servers'
api-version: '1.20'
authors:
  - Spectrasonic

commands:
  animation:
    description: 'Create custom animations'
    aliases:
      - animations
      - animationscore
    permission: animation.cmd
    usage: '/animation <numeric> <frames> <from> <until>'

permissions:
  animation.cmd:
    description: 'Allows usage of animation commands'
    default: op
  animation.*:
    description: 'Grants all animation permissions'
    default: op
    children:
      animation.cmd: true